Repository UruruLab/Ururu-Frontend, pull requests merged in 2025-07, with the labels that each got.

#24 마이페이지 반응형 개선
  src/app/mypage/page.tsx
  src/components/mypage/OrderStatus.tsx
  src/components/mypage/ProfileCard.tsx
Labels: 🌈 FE, 🛠️ Refactor

#25 마이페이지 프로필 수정 UI 구현
  package-lock.json
  package.json
  src/app/login/page.tsx
  src/app/mypage/profile-edit/page.tsx
  src/app/seller-signup/page.tsx
  src/components/form/FormField.tsx
  src/components/mypage/ProfileCard.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/constants/form-styles.ts
  src/constants/validation.ts
  src/hooks/useSignupForm.ts
  src/lib/axios.ts
  src/lib/format-utils.ts
  src/lib/password-utils.ts
  src/lib/utils.ts
Labels: 🌈 FE, 💫 Feature

#27 뷰티 프로필 수정 페이지 UI 구현
  src/app/mypage/beauty-profile-edit/layout.tsx
  src/app/mypage/beauty-profile-edit/page.tsx
  src/app/mypage/profile-edit/page.tsx
  src/components/mypage/ProfileCard.tsx
  src/components/mypage/ShoppingActivities.tsx
  src/components/mypage/index.ts
  src/components/ui/selectable-button.tsx
  src/constants/beauty-profile.ts
  src/constants/form-options.ts
  src/constants/form-styles.ts
  src/constants/validation.ts
  src/hooks/useBeautyProfile.ts
  src/lib/utils.ts
  src/types/form.ts
Labels: 🌈 FE, 💫 Feature

#31 배송지 등록 페이지 UI 구현
  src/app/mypage/address-register/layout.tsx
  src/app/mypage/address-register/page.tsx
  src/components/mypage/MobileSidebarList.tsx
  src/components/mypage/Sidebar.tsx
  src/data/mypage.ts
  src/hooks/useAddressRegister.ts
Labels: 🌈 FE, 💫 Feature

#33 배송지 관리 페이지 UI 구현
  src/app/login/page.tsx
  src/app/mypage/address-register/page.tsx
  src/app/mypage/address/page.tsx
  src/app/mypage/address/register/layout.tsx
  src/app/mypage/address/register/page.tsx
  src/app/mypage/beauty-profile-edit/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile-edit/page.tsx
  src/app/seller-signup/page.tsx
  src/components/layout/search-bar.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/ProfileCard.tsx
  src/components/mypage/address/AddressCard.tsx
  src/components/mypage/address/AddressFormFields.tsx
  src/components/mypage/address/index.ts
  src/components/mypage/beauty-profile-edit/BeautyProfileFormFields.tsx
  src/components/mypage/beauty-profile-edit/index.ts
  src/components/mypage/index.ts
  src/components/mypage/profile-edit/ProfileFormFields.tsx
  src/components/mypage/profile-edit/ProfileImageUpload.tsx
  src/components/mypage/profile-edit/index.ts
  src/constants/form-styles.ts
  src/data/address.ts
  src/data/mypage.ts
  src/hooks/index.ts
  src/hooks/useAddress.ts
  src/hooks/useAddressRegister.ts
  src/hooks/useBeautyProfileEdit.ts
  src/hooks/useMyPage.ts
  src/hooks/useProfileEdit.ts
Labels: 🌈 FE, 💫 Feature, 🛠️ Refactor

#36 모바일 카테고리 선택 페이지 UI 구현
  src/app/category/layout.tsx
  src/app/category/page.tsx
  src/app/examples/custom-layout/page.tsx
  src/app/examples/full-layout/page.tsx
  src/app/examples/minimal-layout/page.tsx
  src/app/examples/no-footer-layout/page.tsx
  src/app/examples/page.tsx
  src/app/test/page.tsx
  src/components/layout/main-nav.tsx
  src/components/ui/index.ts
  src/data/categories.ts
  src/services/test.ts
Labels: 🌈 FE, 💫 Feature

#38 리뷰 작성 페이지 UI 구현
  src/app/mypage/review/page.tsx
  src/app/mypage/review/write/page.tsx
  src/components/mypage/ProfileCard.tsx
  src/components/mypage/index.ts
  src/components/mypage/review/ReviewWriteForm.tsx
  src/components/mypage/review/index.ts
  src/data/mypage.ts
  src/data/review-options.ts
  src/hooks/index.ts
  src/hooks/useReviewWrite.ts
Labels: 🌈 FE, 💫 Feature

#40 상품 상세페이지 구현
  next.config.mjs
  package-lock.json
  package.json
  src/app/product/[id]/page.tsx
  src/components/product/ActionButtons.tsx
  src/components/product/Breadcrumb.tsx
  src/components/product/DetailMain.tsx
  src/components/product/OptionCard.tsx
  src/components/product/OptionSelect.tsx
  src/components/product/OrderBox.tsx
  src/components/product/OrderFloatingBar.tsx
  src/components/product/ProductInfo.tsx
  src/components/product/ProductTabs.tsx
  src/components/product/index.ts
  src/components/ui/index.ts
  src/components/ui/progress.tsx
  src/components/ui/select.tsx
  src/components/ui/selectable-button.tsx
  src/constants/product-detail.ts
  src/data/mock-product.ts
  src/hooks/index.ts
  src/hooks/useImageCarousel.ts
  src/hooks/useProductOptions.ts
Labels: 🌈 FE, 💫 Feature

#43 상품 상세페이지 - 구매정보UI 구현
  src/app/login/page.tsx
  src/app/product/[id]/page.tsx
  src/components/product/ActionButtons.tsx
  src/components/product/DetailMain.tsx
  src/components/product/LoadMoreButton.tsx
  src/components/product/OrderBox.tsx
  src/components/product/OrderFloatingBar.tsx
  src/components/product/ProductDetailImages.tsx
  src/components/product/ProductImage.tsx
  src/components/product/ProductPurchaseInfoSection.tsx
  src/components/product/index.ts
  src/constants/product-constants.ts
  src/constants/product-detail.ts
  src/constants/product-styles.ts
  src/data/mock-product.ts
  src/data/product-info-notice.ts
  src/data/product-info-texts.ts
  src/hooks/index.ts
  src/hooks/useAddress.ts
  src/hooks/useBeautyProfile.ts
  src/hooks/useBeautyProfileEdit.ts
  src/hooks/useImageCarousel.ts
  src/hooks/useProductActions.ts
  src/hooks/useProductDrawer.ts
  src/hooks/useProductImages.ts
  src/hooks/useProductTabs.ts
  src/hooks/useProfileEdit.ts
  src/hooks/useReviewWrite.ts
  src/hooks/useSafeNavigation.ts
  src/lib/axios.ts
  src/types/product.ts
Labels: 🌈 FE, 💫 Feature

#45 장바구니 UI 구현
  src/app/cart/page.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartSelectAll.tsx
  src/components/cart/CartSummary.tsx
  src/components/cart/PriceDisplay.tsx
  src/components/cart/QuantityControl.tsx
  src/components/cart/index.ts
  src/components/layout/header.tsx
  src/data/cart.ts
  src/hooks/index.ts
  src/hooks/useCart.ts
  src/hooks/useCartBadge.ts
  src/lib/cart-utils.ts
  src/types/cart.ts
Labels: 🌈 FE, 💫 Feature

#51 카테고리 랭킹 UI 구현
  src/app/ranking/layout.tsx
  src/app/ranking/page.tsx
  src/components/history/HistoryProductGrid.tsx
  src/components/layout/bottom-navigation.tsx
  src/components/layout/index.ts
  src/components/layout/layouts.tsx
  src/components/layout/main-nav.tsx
  src/components/layout/mobile-nav.tsx
  src/components/layout/navigation-link.tsx
  src/components/product/ProductCard.tsx
  src/components/product/ProductGrid.tsx
  src/components/product/index.ts
  src/components/ranking/CategorySelector.tsx
  src/components/ranking/index.ts
  src/constants/index.ts
  src/constants/navigation.ts
  src/data/ranking.ts
  src/hooks/index.ts
  src/hooks/useRanking.ts
  src/hooks/useSafeNavigation.ts
Labels: 🌈 FE, 💫 Feature

#63 판매자 페이지 UI 구현 및 메인 홈 반응형 개선
  package-lock.json
  package.json
  src/app/event/layout.tsx
  src/app/event/page.tsx
  src/app/history/page.tsx
  src/app/page.tsx
  src/app/product/[id]/page.tsx
  src/app/ranking/page.tsx
  src/app/seller/analytics/page.tsx
  src/app/seller/group-buys/new/page.tsx
  src/app/seller/group-buys/page.tsx
  src/app/seller/layout.tsx
  src/app/seller/orders/page.tsx
  src/app/seller/page.tsx
  src/app/seller/products/new/page.tsx
  src/app/seller/products/page.tsx
  src/app/seller/profile/page.tsx
  src/app/seller/settings/page.tsx
  src/app/shorts/layout.tsx
  src/app/shorts/page.tsx
  src/components/common/EmptyPage.tsx
  src/components/common/index.ts
  src/components/home/PersonalizedSection.tsx
  src/components/product/ProductGrid.tsx
  src/components/seller/GroupBuyRegistration.tsx
  src/components/seller/ProductRegistration.tsx
  src/components/seller/SellerSidebar.tsx
  src/components/seller/common/ActionMenu.tsx
  src/components/seller/common/EmptyPage.tsx
  src/components/seller/common/OptionList.tsx
  src/components/seller/common/PageHeader.tsx
  src/components/seller/common/QuickActionCard.tsx
  src/components/seller/common/SearchFilterBar.tsx
  src/components/seller/common/SectionHeader.tsx
  src/components/seller/common/StatCard.tsx
  src/components/seller/common/StatusBadge.tsx
  src/components/seller/common/index.ts
  src/components/seller/index.ts
  src/components/ui/card.tsx
  src/components/ui/selectable-button.tsx
  src/components/ui/textarea.tsx
  src/constants/form-styles.ts
  src/constants/navigation.ts
  src/data/index.ts
  src/data/seller.ts
  src/hooks/seller/useFormArray.ts
  src/hooks/seller/useImageUpload.ts
Labels: 🌈 FE, 💫 Feature, 🛠️ Refactor

#62 소셜 로그인/인증 상태 전역 관리 및 배포환경 대응
  README.md
  next.config.mjs
  package-lock.json
  package.json
  src/app/AuthHydrator.tsx
  src/app/auth/error/page.tsx
  src/app/auth/success/page.tsx
  src/app/cart/page.tsx
  src/app/history/page.tsx
  src/app/layout.tsx
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/orders/page.tsx
  src/app/mypage/page.tsx
  src/app/order/page.tsx
  src/components/common/LoadingSkeleton.tsx
  src/components/common/index.ts
  src/components/layout/header.tsx
  src/components/layout/top-bar.tsx
  src/components/mypage/MobileSidebarList.tsx
  src/components/mypage/ProfileCard.tsx
  src/components/mypage/Sidebar.tsx
  src/components/ui/index.ts
  src/components/ui/skeleton.tsx
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/hooks/useAuthGuard.ts
  src/hooks/useLogout.ts
  src/hooks/useMyPage.ts
  src/hooks/useSocialLogin.ts
  src/lib/axios.ts
  src/services/auth.ts
  src/store/auth.ts
  src/types/api.ts
Labels: 🌈 FE, 💫 Feature

#70 회원 정보 조회 및 수정 관련 API 연동
  package-lock.json
  package.json
  src/app/mypage/beauty-profile-edit/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile-edit/page.tsx
  src/components/common/ErrorDialog.tsx
  src/components/common/SuccessDialog.tsx
  src/components/common/index.ts
  src/components/mypage/ProfileCard.tsx
  src/components/mypage/beauty-profile-edit/BeautyProfileFormFields.tsx
  src/components/mypage/beauty-profile/BeautyProfileSummary.tsx
  src/components/mypage/profile-edit/ProfileFormFields.tsx
  src/components/ui/dialog.tsx
  src/components/ui/index.ts
  src/constants/beauty-profile.ts
  src/constants/form-styles.ts
  src/hooks/useBeautyProfileEdit.ts
  src/hooks/useProfileEdit.ts
  src/services/beautyProfileService.ts
  src/services/memberService.ts
  src/types/auth.ts
  src/types/form.ts
Labels: 🌈 FE, 💫 Feature

#83 회원 배송지 관리 API 연동
  src/app/mypage/address/page.tsx
  src/app/mypage/address/register/page.tsx
  src/components/mypage/address/AddressCard.tsx
  src/components/mypage/address/AddressFormFields.tsx
  src/data/address.ts
  src/hooks/index.ts
  src/hooks/useAddress.ts
  src/hooks/useAddressList.ts
  src/services/memberService.ts
  src/types/api.ts
Labels: 🌈 FE, 💫 Feature

#85 상품 관리 페이지에서 상품 조회 API 연동 및 UI/UX 디자인
  src/app/seller/products/page.tsx
  src/components/seller/ProductManagement.tsx
  src/components/seller/ProductRegistration.tsx
  src/components/seller/common/Pagination.tsx
  src/components/seller/index.ts
  src/services/productService.ts
  src/types/product.ts
Labels: 🌈 FE, 💫 Feature

#87 상품 상세 조회 API 연동 및 UI/UX 디자인
  src/app/seller/products/[id]/page.tsx
  src/components/seller/ProductDetail.tsx
  src/components/seller/ProductManagement.tsx
  src/components/seller/ProductRegistration.tsx
  src/components/seller/index.ts
  src/services/productService.ts
  src/types/product.ts
Labels: 🌈 FE, 💫 Feature

#92 마이페이지 주문/포인트 내역 조회 API 연동
  next.config.mjs
  src/app/mypage/orders/page.tsx
  src/app/mypage/point/page.tsx
  src/components/common/OrderActionButtons.tsx
  src/components/common/RewardBadge.tsx
  src/components/orders/OrderCard.tsx
  src/data/orders.ts
  src/hooks/index.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useOrders.ts
  src/hooks/usePointHistory.ts
  src/lib/utils.ts
  src/services/orderService.ts
  src/services/pointService.ts
  src/types/order.ts
  src/types/point.ts
Labels: 🌈 FE, 💫 Feature

#95 랭킹 TOP100 페이지 API 연동
  src/app/ranking/page.tsx
  src/hooks/useRanking.ts
  src/services/groupbuyService.ts
  src/types/groupbuy.ts
Labels: 🌈 FE, 💫 Feature

#101 마이페이지 환불 내역 조회 API 연동
  src/app/mypage/refunds/page.tsx
  src/components/common/StatusBadge.tsx
  src/components/refunds/RefundCard.tsx
  src/components/refunds/RefundStatusTabs.tsx
  src/hooks/index.ts
  src/hooks/useRefunds.ts
  src/lib/format-utils.ts
  src/lib/utils.ts
  src/services/refundService.ts
  src/types/refund.ts
Labels: 🌈 FE, 💫 Feature

#103 공동구매 등록 API 연동 및 UI/UX
  src/app/seller/group-buys/new/page.tsx
  src/components/seller/GroupBuyRegistration.tsx
  src/components/seller/ProductDetail.tsx
  src/components/seller/ProductManagement.tsx
  src/components/seller/common/DiscountTierCard.tsx
  src/components/seller/common/ImageUploadField.tsx
  src/services/groupbuyService.ts
  src/types/groupbuy.ts
Labels: 🌈 FE, 💫 Feature

#100 세부 카테고리 별 API 연동
  src/app/category/page.tsx
  src/components/layout/main-nav.tsx
  src/components/product/ProductGrid.tsx
  src/components/ranking/CategorySelector.tsx
  src/services/groupbuyService.ts
Labels: 🌈 FE, 💫 Feature

#106 공동구매 상세 조회 (구매자용) API 연동 및 UI/UX
  src/app/groupbuys/[id]/page.tsx
  src/app/product/[id]/page.tsx
  src/components/product/Breadcrumb.tsx
  src/components/product/DetailMain.tsx
  src/components/product/OptionCard.tsx
  src/components/product/OptionSelect.tsx
  src/components/product/OrderBox.tsx
  src/components/product/OrderFloatingBar.tsx
  src/components/product/ProductCard.tsx
  src/components/product/ProductDetailImages.tsx
  src/components/product/ProductInfo.tsx
  src/components/product/ProductPurchaseInfoSection.tsx
  src/components/product/index.ts
  src/constants/product-detail.ts
  src/hooks/useProductImages.ts
  src/hooks/useProductOptions.ts
  src/services/groupbuyService.ts
  src/types/groupbuy.ts
  src/types/product.ts
Labels: 🌈 FE, 💫 Feature

#110 작업 결제 요청 → 승인 전체 플로우 API 연동
  package-lock.json
  package.json
  src/app/api/payment/approve/route.ts
  src/app/api/payments/fail/route.ts
  src/app/auth/callback/page.tsx
  src/app/mypage/page.tsx
  src/app/order/[orderId]/page.tsx
  src/app/payment/fail/page.tsx
  src/app/payment/success/page.tsx
  src/components/auth/AuthGuard.tsx
  src/components/mypage/ProfileCard.tsx
  src/components/payment/PaymentWidget.tsx
  src/components/payment/PaymentWindow.tsx
  src/components/product/ProductCard.tsx
  src/hooks/usePayment.ts
  src/services/paymentService.ts
  src/services/tossPaymentsService.ts
  src/utils/paymentErrorMapping.ts
Labels: 🌈 FE, 💫 Feature

#112 공동구매 판매자용 목록 조회 및 공동구매 상태 변경 API 연동
  src/app/groupbuys/[id]/page.tsx
  src/app/mypage/address/page.tsx
  src/app/seller/group-buys/page.tsx
  src/components/home/ProductRankingItem.tsx
  src/components/seller/GroupBuyManagement.tsx
  src/components/seller/GroupBuyRegistration.tsx
  src/components/seller/index.ts
  src/hooks/useAddressList.ts
  src/hooks/useCart.ts
  src/hooks/usePayment.ts
  src/services/groupbuyService.ts
  src/types/groupbuy.ts
Labels: 🌈 FE, 💫 Feature

#113 공구 상세 페이지 장바구니/주문 API 연동
  src/app/layout.tsx
  src/components/product/ActionButtons.tsx
  src/components/product/OrderBox.tsx
  src/components/product/OrderFloatingBar.tsx
  src/hooks/useProductActions.ts
  src/services/cartService.ts
  src/services/groupbuyService.ts
  src/types/api.ts
Labels: 🌈 FE, 💫 Feature
